# Generated by Django 4.2.4 on 2023-08-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0002_alter_qrcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='user',
        ),
    ]
